package constant

var (
	ZeroReadAs               = "ศูนย์"
	OneReadAs                = "หนึ่ง"
	TwoReadAs                = "สอง"
	ThreeReadAs              = "สาม"
	FourReadAs               = "สี่"
	FiveReadAs               = "ห้า"
	SixReadAs                = "หก"
	SevenReadAs              = "เจ็ด"
	EightReadAs              = "แปด"
	NineReadAs               = "เก้า"
	TenReadAs                = "สิบ"
	TwentyReadAs             = "ยี่"
	MillionReadAs            = "ล้าน"
	OneHundredThousandReadAs = "แสน"
	TenThousandReadAS        = "หมื่น"
	OneThousandReadAs        = "พัน"
	OneHundredReadAs         = "ร้อย"
	LastDigitOne             = ""
	LastDigitOneReadAs       = "เอ็ด"
	Baht                     = "บาท"
	Stang                    = "สตางค์"
	Total                    = "ถ้วน"

	Zero               = "0"
	One                = "1"
	Two                = "2"
	Three              = "3"
	Four               = "4"
	Five               = "5"
	Six                = "6"
	Seven              = "7"
	Eight              = "8"
	Nine               = "9"
	Ten                = "10"
	Twenty             = "20"
	OneHundredThousand = "100000"
	TenThousand        = "10000"
	OneThousand        = "1000"
	OneHundred         = "100"
)
